name: Jukebox CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar arquivo .env para o Docker
        run: |
          echo "SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}" >> .env
          echo "SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> .env
          echo "SPOTIFY_REFRESH_TOKEN=${{ secrets.SPOTIFY_REFRESH_TOKEN }}" >> .env

      - name: Rodar ambiente e Testes Cypress
        run: |
          docker compose up --build --exit-code-from cypress

      - name: Upload de evidências (Screenshots/Vídeos) em caso de falha
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-evidences
          path: |
            jukebox-test/cypress/screenshots
            jukebox-test/cypress/videos